server:
  port: 9093

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false  
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  service:
    wait-time-in-ms-when-sync-empty: 3000


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root1234
    platform: mysql
    url: jdbc:mysql://springcloud.cqjgc0jmeyma.us-east-1.rds.amazonaws.com:3306/testEurekaDB?verifyServerCertificate=false&useSSL=false&requireSSL=false #url de acesso ao banco de dados
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
